- name: restart nginx
  action: systemd name=nginx state=restarted
  become: yes

- name: restart php7.0-fpm
  action: systemd name=php7.0-fpm state=restarted
  become: yes

- name: restart atd
  action: systemd name=atd state=restarted
  become: yes

- name: restart avahi-daemon
  action: systemd name=avahi-daemon state=restarted
  become: yes
