- name : check twitter crawler service systemd script exists.
  stat: path=/etc/systemd/system/airpippi-twitter-crawler.service
  register: crawler

- name: disable twitter crawler service
  systemd:
    name: "airpippi-twitter-crawler"
    daemon-reload: yes
    enabled: no
    state: stopped
  when: crawler.stat.exists
  become: yes

- name: remove twitter crawler service systemd script
  file:
    path: /etc/systemd/system/airpippi-twitter-crawler.service
    state: absent
  become: yes
