- name: install NetworkManager
  apt: >
    name=network-manager
    state=present
    update_cache=yes
    cache_valid_time=3600
  become: yes

- name: uninstall oldtype network management tool
  apt: >
    name={{ item }}
    state=absent
  with_items:
    - dhcpcd5
    - ifplugd
  become: yes

- name: copy wi-fi configuration
  template: >
    src=wifi.j2
    dest=/etc/NetworkManager/system-connections/{{ item.ssid }}
    mode=0600
    owner=root
    group=root
  with_items: "{{ wifi }}"
  become: yes
  notify: restart network-manager

- name: clear network config fies
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    backup=yes
  with_items:
    - src: interfaces
      dest: /etc/network/interfaces
    - src: wpa_supplicant.conf
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
  become: yes
